import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About me page ",
  description: "Generated by About Me Page ",
};

export default function AboutLayout({ children }:any) {
  return (
    <div>
      <header>About Page Header</header>
      <main>{children}</main>
      <footer>About Page Footer</footer>
    </div>
  );
}