import type { Metadata } from "next";
import { ReactNode } from "react";
export const metadata: Metadata = {
  title: "About me page ",
  description: "Generated by About Me Page ",
};


interface AboutLayoutProps {
  children: ReactNode;
} 
export default function AboutLayout({ children}:AboutLayoutProps) {
  return (
    <div>
      <header>About Page Header</header>
      <main>{children}</main>
      <footer>About Page Footer</footer>
    </div>
  );
}